### ISSUE TITLE
Compiling issue on g++4.6.4

### ISSUE THREAD

**Issue by suvirbhargav** [whoshuu/cpr-example#2]
works fine on modern g++. But it does not compile on g++4.6.4 which had only experimental c++11 support.
Here is the error
```
make
Scanning dependencies of target cpr
[  9%] Building CXX object opt/cpr/cpr/CMakeFiles/cpr.dir/auth.cpp.o
[ 18%] Building CXX object opt/cpr/cpr/CMakeFiles/cpr.dir/cookies.cpp.o
[ 27%] Building CXX object opt/cpr/cpr/CMakeFiles/cpr.dir/cprtypes.cpp.o
[ 36%] Building CXX object opt/cpr/cpr/CMakeFiles/cpr.dir/digest.cpp.o
[ 45%] Building CXX object opt/cpr/cpr/CMakeFiles/cpr.dir/multipart.cpp.o
In file included from /home/m/Desktop/working/curl/new_cpr/cpr-example/opt/cpr/cpr/multipart.cpp:1:0:
/home/m/Desktop/working/curl/new_cpr/cpr-example/opt/cpr/include/multipart.h:16:97: error: expected primary-expression before ‘{’ token
/home/m/Desktop/working/curl/new_cpr/cpr-example/opt/cpr/include/multipart.h:18:89: error: expected primary-expression before ‘{’ token
/home/m/Desktop/working/curl/new_cpr/cpr-example/opt/cpr/include/multipart.h:20:89: error: expected primary-expression before ‘{’ token
make[2]: *** [opt/cpr/cpr/CMakeFiles/cpr.dir/multipart.cpp.o] Error 1
make[1]: *** [opt/cpr/cpr/CMakeFiles/cpr.dir/all] Error 2
make: *** [all] Error 2


m@m-VirtualBox:~/Desktop/working/curl/cpr-example/build$ g++ --version
g++ (Ubuntu/Linaro 4.6.4-1ubuntu1~12.04) 4.6.4
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
cmake output
```
m@m-VirtualBox:~/Desktop/working/curl/cpr-example/build$ cmake ..
-- Checking compiler flags for C++11 support.
-- C++0x is supported.
-- Checking compiler flags for C++11 support.
-- C++0x is supported.
-- C++ Requests CMake Options
-- =======================================================
--   USE_SYSTEM_CURL: ON
--   BUILD_CPR_TESTS: OFF
--   INSECURE_CURL: OFF
--   GENERATE_COVERAGE: OFF
--   USE_SYSTEM_GTEST: OFF
-- =======================================================
-- Set CURL_FOUND to TRUE.
-- Set CURL_LIBRARIES to /usr/lib/i386-linux-gnu/libcurl.so.
-- Set CURL_INCLUDE_DIRS to /usr/include.
-- Using CURL_INCLUDE_DIRS: /usr/include.
-- Using CURL_LIBRARIES: /usr/lib/i386-linux-gnu/libcurl.so.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/m/Desktop/working/curl/cpr-example/build

```
Just thought to report.

**Comment by whoshuu** [comment]
Thanks for the report. This actually might be rectifiable without much finagling, I'll take a look at it some time this week in the library repo.

**Comment by suvirbhargav** [comment]
Doesn't look so doable on 4.6 compiler. The complete c++11 support was introduced in gcc from 4.7. So, i changed to 4.7 and it compiles fine.

```
cpr-example/build$ g++ --version
g++ (Ubuntu/Linaro 4.7.3-2ubuntu1~12.04) 4.7.3
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

~/Desktop/curl/cpr-example/build$ ./example 
{
    "args": {},
    "headers": {
        "Accept": "*/*",
        "Host": "httpbin.org",
        "User-Agent": "curl/7.22.0"

```

For the reported error above, i changed the string initialization to const std::string& content_type  only. With 4.6 having experimental support, it leads to tons of other errors all over even after fixing the above one.

**Comment by suvirbhargav** [comment]
It could be that not many developers are using any compiler below than 4.7. Sorry for the accidental open/close button hit.

**Comment by whoshuu** [comment]
I'm gonna set up an automatic build of this example project under gcc 4.6, and have it be an allowable failure. That'll provide documented insight into the gap between this and 4.7. If I can manage that, should we close this issue?

**Comment by suvirbhargav** [comment]
yes, sounds good.
